-- plugins/formatter.lua (or wherever your plugin list is)
return {
  -- 'nvimtools/none-ls.nvim',
  -- event = { 'BufReadPre', 'BufNewFile' },
  -- config = function()
  --   local null_ls = require 'null-ls'
  --   local augroup = vim.api.nvim_create_augroup('LspFormatting', {})
  --
  --   null_ls.setup {
  --     sources = {
  --       -- cpp
  --       -- null_ls.builtins.formatting.clang_format,
  --       -- go
  --       null_ls.builtins.formatting.gofumpt,
  --       null_ls.builtins.formatting.goimports_reviser,
  --       null_ls.builtins.formatting.golines,
  --     },
  --     -- auto format on save
  --     on_attach = function(client, bufnr)
  --       local filetype = vim.bo[bufnr].filetype
  --       if client.name == 'ols' or filetype == 'odin' then
  --         return
  --       end
  --
  --       if client.supports_method 'textDocument/formatting' then
  --         vim.api.nvim_clear_autocmds {
  --           group = augroup,
  --           buffer = bufnr,
  --         }
  --         vim.api.nvim_create_autocmd('BufWritePre', {
  --           group = augroup,
  --           buffer = bufnr,
  --           callback = function()
  --             vim.lsp.buf.format { bufnr = bufnr }
  --           end,
  --         })
  --       end
  --     end,
  --   }
  -- end,
}
